name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-test.txt
      - name: Run Tests
        run: |
          pytest --cov=src --cov-report=term --cov-report=xml --cov-config=.coveragerc
          cp coverage.xml /tmp/pr_coverage.xml
          rm coverage.xml
      - name: Run Base Coverage
        if: github.event_name == 'pull_request'
        run: |
          git checkout --progress --force "${{ github.event.pull_request.base.sha }}"
          pytest --cov=src --cov-report=term --cov-report=xml --cov-config=.coveragerc
          cp coverage.xml /tmp/base_coverage.xml
          rm coverage.xml
          git checkout --progress --force "$GITHUB_SHA"
      - name: Enforce Coverage Non-Regression
        if: github.event_name == 'pull_request'
        run: python scripts/coverage_guard.py --base /tmp/base_coverage.xml --pr /tmp/pr_coverage.xml
